INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /users/user_summaries_for_dashboard/
Traceback (most recent call last):
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/authentication.py", line 120, in inner
    data, statuscode = view_func(request, *args, **kwargs) # Main login
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/authentication.py", line 144, in inner
    result, code = func(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py", line 333, in summaries_for_dashboard
    logger.info("checking")
AttributeError: 'NoneType' object has no attribute 'info'
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /users/user_summaries_for_dashboard/
Traceback (most recent call last):
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/authentication.py", line 120, in inner
    data, statuscode = view_func(request, *args, **kwargs) # Main login
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/authentication.py", line 144, in inner
    result, code = func(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py", line 355, in summaries_for_dashboard
    sum_of_submitted = expenses.filter(status=True).only('amount').sum()
AttributeError: 'QuerySet' object has no attribute 'sum'
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /users/user_summaries_for_dashboard/
Traceback (most recent call last):
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/authentication.py", line 120, in inner
    data, statuscode = view_func(request, *args, **kwargs) # Main login
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/authentication.py", line 144, in inner
    result, code = func(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py", line 362, in summaries_for_dashboard
    result = json.dumps(result)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type QuerySet is not JSON serializable
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /users/user_summaries_for_dashboard/
Traceback (most recent call last):
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/authentication.py", line 120, in inner
    data, statuscode = view_func(request, *args, **kwargs) # Main login
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/authentication.py", line 144, in inner
    result, code = func(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py", line 355, in summaries_for_dashboard
    sum_of_submitted = expenses.filter(status=True).only('amount').first().__dict__
AttributeError: 'NoneType' object has no attribute '__dict__'
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /users/user_summaries_for_dashboard/
Traceback (most recent call last):
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/authentication.py", line 120, in inner
    data, statuscode = view_func(request, *args, **kwargs) # Main login
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/authentication.py", line 144, in inner
    result, code = func(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py", line 363, in summaries_for_dashboard
    result = json.dumps(result)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type QuerySet is not JSON serializable
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /users/user_summaries_for_dashboard/
Traceback (most recent call last):
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/authentication.py", line 120, in inner
    data, statuscode = view_func(request, *args, **kwargs) # Main login
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/authentication.py", line 144, in inner
    result, code = func(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py", line 355, in summaries_for_dashboard
    sum_of_submitted = expenses.filter(status='pending').only('amount').sum()
AttributeError: 'QuerySet' object has no attribute 'sum'
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /users/user_summaries_for_dashboard/
Traceback (most recent call last):
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/authentication.py", line 120, in inner
    data, statuscode = view_func(request, *args, **kwargs) # Main login
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/authentication.py", line 144, in inner
    result, code = func(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py", line 357, in summaries_for_dashboard
    print(sum_of_submitted['amount__sum'].round(2))
AttributeError: 'decimal.Decimal' object has no attribute 'round'
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /users/user_summaries_for_dashboard/
Traceback (most recent call last):
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/authentication.py", line 120, in inner
    data, statuscode = view_func(request, *args, **kwargs) # Main login
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/authentication.py", line 144, in inner
    result, code = func(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py", line 364, in summaries_for_dashboard
    result = json.dumps(result)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Decimal is not JSON serializable
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /users/user_summaries_for_dashboard/
Traceback (most recent call last):
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/authentication.py", line 120, in inner
    data, statuscode = view_func(request, *args, **kwargs) # Main login
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/authentication.py", line 144, in inner
    result, code = func(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py", line 357, in summaries_for_dashboard
    result['sum_of_submitted_expenses'] = float(round(sum_of_submitted['amount__sum'], 2))
TypeError: type NoneType doesn't define __round__ method
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /users/user_summaries_for_dashboard/
Traceback (most recent call last):
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/authentication.py", line 120, in inner
    data, statuscode = view_func(request, *args, **kwargs) # Main login
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/authentication.py", line 144, in inner
    result, code = func(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py", line 357, in summaries_for_dashboard
    result['sum_of_submitted_expenses'] = float(round(sum_of_submitted['amount__sum'], 2))
TypeError: type NoneType doesn't define __round__ method
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /users/user_summaries_for_dashboard/
Traceback (most recent call last):
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/authentication.py", line 120, in inner
    data, statuscode = view_func(request, *args, **kwargs) # Main login
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/authentication.py", line 144, in inner
    result, code = func(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py", line 357, in summaries_for_dashboard
    result['sum_of_submitted_expenses'] = float(round(sum_of_submitted['amount__sum'], 2)) if sum_of_submitted else 0
TypeError: type NoneType doesn't define __round__ method
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /users/user_summaries_for_dashboard/
Traceback (most recent call last):
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/authentication.py", line 120, in inner
    data, statuscode = view_func(request, *args, **kwargs) # Main login
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/authentication.py", line 144, in inner
    result, code = func(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py", line 363, in summaries_for_dashboard
    result['sum_of_pending_expenses'] = float(round(sum_of_submitted['amount__sum'], 2)) if sum_of_pending['amount__sum']  else 0
TypeError: type NoneType doesn't define __round__ method
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /users/user_summaries_for_dashboard/
Traceback (most recent call last):
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/authentication.py", line 120, in inner
    data, statuscode = view_func(request, *args, **kwargs) # Main login
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/authentication.py", line 144, in inner
    result, code = func(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py", line 363, in summaries_for_dashboard
    result['sum_of_pending_expenses'] = float(round(sum_of_submitted['amount__sum'], 2)) if sum_of_pending['amount__sum']  else 0
TypeError: type NoneType doesn't define __round__ method
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /users/user_summaries_for_dashboard/
Traceback (most recent call last):
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/authentication.py", line 120, in inner
    data, statuscode = view_func(request, *args, **kwargs) # Main login
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/authentication.py", line 144, in inner
    result, code = func(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py", line 363, in summaries_for_dashboard
    result['sum_of_pending_expenses'] = float(round(sum_of_submitted['amount__sum'], 2)) if sum_of_pending['amount__sum'] is not None  else 0
TypeError: type NoneType doesn't define __round__ method
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /users/user_summaries_for_dashboard/
Traceback (most recent call last):
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/authentication.py", line 120, in inner
    data, statuscode = view_func(request, *args, **kwargs) # Main login
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/authentication.py", line 144, in inner
    result, code = func(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py", line 363, in summaries_for_dashboard
    result['sum_of_pending_expenses'] = float(round(sum_of_submitted['amount__sum'], 2)) if sum_of_pending['amount__sum'] is not None  else 0
TypeError: type NoneType doesn't define __round__ method
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
WARNING:django.request:Not Found: /users/summaries_for_dashboard
WARNING:django.request:Not Found: /users/summaries_for_dashboard
WARNING:django.request:Not Found: /users/summaries_for_dashboard
WARNING:django.request:Not Found: /users/summaries_for_dashboard
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /users/user_summaries_for_dashboard/
Traceback (most recent call last):
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/authentication.py", line 120, in inner
    data, statuscode = view_func(request, *args, **kwargs) # Main login
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/authentication.py", line 144, in inner
    result, code = func(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py", line 359, in summaries_for_dashboard
    result['sum_of_submitted_expenses'] = [float(round(sum_, 2)) if sum_of_submitted['amount__sum'] is not None else 0, sum_of_submitted.count()]
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/db/models/query.py", line 418, in __getitem__
    raise TypeError(
TypeError: QuerySet indices must be integers or slices, not str.
ERROR:django.request:Internal Server Error: /users/user_summaries_for_dashboard/
Traceback (most recent call last):
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/authentication.py", line 120, in inner
    data, statuscode = view_func(request, *args, **kwargs) # Main login
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/authentication.py", line 144, in inner
    result, code = func(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py", line 359, in summaries_for_dashboard
    result['sum_of_submitted_expenses'] = [float(round(sum_, 2)) if sum_of_submitted['amount__sum'] is not None else 0, sum_of_submitted.count()]
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/db/models/query.py", line 418, in __getitem__
    raise TypeError(
TypeError: QuerySet indices must be integers or slices, not str.
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /users/user_summaries_for_dashboard/
Traceback (most recent call last):
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/authentication.py", line 120, in inner
    data, statuscode = view_func(request, *args, **kwargs) # Main login
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/authentication.py", line 144, in inner
    result, code = func(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py", line 359, in summaries_for_dashboard
    result['sum_of_submitted_expenses'] = [float(round(sum_, 2)) if sum_of_submitted['amount__sum'] is not None else 0, sum_of_submitted.count()]
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/db/models/query.py", line 418, in __getitem__
    raise TypeError(
TypeError: QuerySet indices must be integers or slices, not str.
ERROR:django.request:Internal Server Error: /users/user_summaries_for_dashboard/
Traceback (most recent call last):
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/authentication.py", line 120, in inner
    data, statuscode = view_func(request, *args, **kwargs) # Main login
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/authentication.py", line 144, in inner
    result, code = func(request, *args, **kwargs)
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py", line 359, in summaries_for_dashboard
    result['sum_of_submitted_expenses'] = [float(round(sum_, 2)) if sum_of_submitted['amount__sum'] is not None else 0, sum_of_submitted.count()]
  File "/Users/ramchandrab/Documents/expense_tracker/expensetracker/venv/lib/python3.10/site-packages/django/db/models/query.py", line 418, in __getitem__
    raise TypeError(
TypeError: QuerySet indices must be integers or slices, not str.
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/ramchandrab/Documents/expense_tracker/expensetracker/Users/views.py changed, reloading.
WARNING:django.request:Not Found: //ExpenseMedia/profilepics/default.png
WARNING:django.request:Not Found: //ExpenseMedia/profilepics/default.png
WARNING:django.request:Not Found: //ExpenseMedia/profilepics/default.png
